import { useRef } from 'react'
import FilePreviewCard from './FilePreviewCard'

const AUTO_GENERATED_NAME_PATTERNS = [
  /^original[-_]?[0-9a-f]{16,}$/i,
  /^[0-9a-f]{16,}$/i,
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i,
  /^(img|vid|video|audio|file|download|whatsapp|status|voice|rec)[-_ ]?\d{2,}$/i,
  /^\d{10,}$/,
]

function looksAutoGenerated(name) {
  const trimmed = name.trim()
  if (!trimmed) return false
  return AUTO_GENERATED_NAME_PATTERNS.some((re) => re.test(trimmed))
}

// authorLabel: "Author" | "Tutor" | "Artist" — computed once in
// SubmitResource.jsx from the resource type selected in Step 1, passed
// straight through to every file card's modal.
function MultiFileUpload({ files, onFilesChange, accept, authorLabel = 'Author', categories = [], onCreateCategory, resourceTypeSlug }) {
  const inputRef = useRef(null)

  const handleSelect = (e) => {
    const newFiles = Array.from(e.target.files).map((file) => {
      const stripped = file.name.replace(/\.[^/.]+$/, '')
      // PDFs and images go through AI analysis (see FilePreviewCard.jsx's
      // ANALYZABLE_KINDS) — leave name blank for those regardless of how
      // the filename looks, so the AI's real detected title (or, failing
      // that, its own filename-based fallback from the backend) has
      // somewhere to land. Pre-filling here would always win over the
      // AI's answer, since AI suggestions only apply to an empty field.
      const isAnalyzable = file.type === 'application/pdf' || file.type.startsWith('image/')
      return {
        file,
        name: isAnalyzable ? '' : (looksAutoGenerated(stripped) ? '' : stripped),
        author: '',
        categoryId: '',
        courseCode: '',
        description: '',
        tags: '',
        thumbnailBlob: null, // NEW — filled in once FilePreviewCard finishes client-side rendering
        chapter: '',
        part: '',
        volume: '',
        edition: '',
        collectionMatch: null, // NEW — { collectionId, title, author, score, confidence } from /analyze's `detected`, or null
        collectionChoice: null, // NEW — 'use' | 'other' | 'none' | null (user hasn't decided yet)
      }
    })
    onFilesChange([...files, ...newFiles])
    e.target.value = ''
  }

  // Functional update form — critical when several fields get set in
  // rapid succession from the same synchronous callback (see
  // FilePreviewCard.jsx's AI-suggestion handler, which calls onXChange
  // for name/author/description/tags/category one after another with no
  // render in between). Building the new array from the CLOSURE's
  // `files` (as this used to) meant every call in that burst computed
  // its patch against the same stale array, so only the last call's
  // change actually survived — every earlier one got silently
  // overwritten. Passing a function to onFilesChange (React's setState
  // updater form) makes each call build on the true latest state
  // instead, so all six updates stack correctly.
  const updateFile = (index, patch) => {
    onFilesChange((prevFiles) => prevFiles.map((f, i) => (i === index ? { ...f, ...patch } : f)))
  }

  const removeFile = (index) => {
    onFilesChange(files.filter((_, i) => i !== index))
  }

  return (
    <div className="flex flex-col gap-stack-md">
      {files.map((entry, index) => (
        <FilePreviewCard
          key={`${entry.file.name}-${entry.file.size}-${index}`}
          file={entry.file}
          name={entry.name}
          author={entry.author}
          authorLabel={authorLabel}
          categoryId={entry.categoryId}
          courseCode={entry.courseCode}
          description={entry.description}
          tags={entry.tags}
          chapter={entry.chapter}
          part={entry.part}
          volume={entry.volume}
          edition={entry.edition}
          collectionMatch={entry.collectionMatch}
          collectionChoice={entry.collectionChoice}
          categories={categories}
          resourceTypeSlug={resourceTypeSlug}
          onNameChange={(name) => updateFile(index, { name })}
          onAuthorChange={(author) => updateFile(index, { author })}
          onCategoryIdChange={(categoryId) => updateFile(index, { categoryId })}
          onCourseCodeChange={(courseCode) => updateFile(index, { courseCode })}
          onDescriptionChange={(description) => updateFile(index, { description })}
          onTagsChange={(tags) => updateFile(index, { tags })}
          onChapterChange={(chapter) => updateFile(index, { chapter })}
          onPartChange={(part) => updateFile(index, { part })}
          onVolumeChange={(volume) => updateFile(index, { volume })}
          onEditionChange={(edition) => updateFile(index, { edition })}
          onCollectionMatchChange={(collectionMatch) => updateFile(index, { collectionMatch })}
          onCollectionChoiceChange={(collectionChoice) => updateFile(index, { collectionChoice })}
          onCreateCategory={onCreateCategory}
          onThumbnailChange={(blob) => updateFile(index, { thumbnailBlob: blob })}
          onRemove={() => removeFile(index)}
        />
      ))}

      <button
        onClick={() => inputRef.current?.click()}
        className="flex flex-col items-center justify-center gap-2 h-28 rounded-xl border border-dashed border-outline bg-surface-container cursor-pointer hover:border-on-surface-variant transition-colors"
      >
        <span className="material-symbols-outlined text-on-surface-variant text-2xl">upload_file</span>
        <span className="font-label-md text-label-md text-on-surface-variant">
          {files.length === 0 ? 'Tap to select files' : 'Add more files'}
        </span>
      </button>

      <input ref={inputRef} type="file" multiple accept={accept} onChange={handleSelect} className="hidden" />
    </div>
  )
}

export default MultiFileUpload