import { useRef } from 'react'
import FilePreviewCard from './FilePreviewCard'

const AUTO_GENERATED_NAME_PATTERNS = [
  /^original[-_]?[0-9a-f]{16,}$/i,
  /^[0-9a-f]{16,}$/i,
  /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i,
  /^(img|vid|video|audio|file|download|whatsapp|status|voice|rec)[-_ ]?\d{2,}$/i,
  /^\d{10,}$/,
]

function looksAutoGenerated(name) {
  const trimmed = name.trim()
  if (!trimmed) return false
  return AUTO_GENERATED_NAME_PATTERNS.some((re) => re.test(trimmed))
}

// authorLabel: "Author" | "Tutor" | "Artist" — computed once in
// SubmitResource.jsx from the resource type selected in Step 1, passed
// straight through to every file card's modal.
function MultiFileUpload({ files, onFilesChange, accept, authorLabel = 'Author', categories = [], onCreateCategory }) {
  const inputRef = useRef(null)

  const handleSelect = (e) => {
    const newFiles = Array.from(e.target.files).map((file) => {
      const stripped = file.name.replace(/\.[^/.]+$/, '')
      return {
        file,
        name: looksAutoGenerated(stripped) ? '' : stripped,
        author: '',
        categoryId: '',
        courseCode: '',
        description: '',
        thumbnailBlob: null, // NEW — filled in once FilePreviewCard finishes client-side rendering
      }
    })
    onFilesChange([...files, ...newFiles])
    e.target.value = ''
  }

  const updateFile = (index, patch) => {
    onFilesChange(files.map((f, i) => (i === index ? { ...f, ...patch } : f)))
  }

  const removeFile = (index) => {
    onFilesChange(files.filter((_, i) => i !== index))
  }

  return (
    <div className="flex flex-col gap-stack-md">
      {files.map((entry, index) => (
        <FilePreviewCard
          key={`${entry.file.name}-${entry.file.size}-${index}`}
          file={entry.file}
          name={entry.name}
          author={entry.author}
          authorLabel={authorLabel}
          categoryId={entry.categoryId}
          courseCode={entry.courseCode}
          description={entry.description}
          categories={categories}
          onNameChange={(name) => updateFile(index, { name })}
          onAuthorChange={(author) => updateFile(index, { author })}
          onCategoryIdChange={(categoryId) => updateFile(index, { categoryId })}
          onCourseCodeChange={(courseCode) => updateFile(index, { courseCode })}
          onDescriptionChange={(description) => updateFile(index, { description })}
          onCreateCategory={onCreateCategory}
          onThumbnailChange={(blob) => updateFile(index, { thumbnailBlob: blob })}
          onRemove={() => removeFile(index)}
        />
      ))}

      <button
        onClick={() => inputRef.current?.click()}
        className="flex flex-col items-center justify-center gap-2 h-28 rounded-xl border border-dashed border-outline bg-surface-container cursor-pointer hover:border-on-surface-variant transition-colors"
      >
        <span className="material-symbols-outlined text-on-surface-variant text-2xl">upload_file</span>
        <span className="font-label-md text-label-md text-on-surface-variant">
          {files.length === 0 ? 'Tap to select files' : 'Add more files'}
        </span>
      </button>

      <input ref={inputRef} type="file" multiple accept={accept} onChange={handleSelect} className="hidden" />
    </div>
  )
}

export default MultiFileUpload